# Generated by Django 2.2.3 on 2019-07-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=30)),
                ('img', models.ImageField(blank=True, default='img/turtle1.jpg', null=True, upload_to='img')),
                ('salt', models.CharField(max_length=20, null=True)),
                ('regist_time', models.CharField(max_length=32, null=True)),
                ('access_time', models.CharField(max_length=32, null=True)),
            ],
        ),
    ]
